baseURL = "https://ericktornero.github.io/blog/"
languageCode = "en-us"
title = "Research blog"
theme = "indigo"
publishDir = "docs"

[params]
    Author      =   "Erick Tornero"
    Description = "Erick Tornero, Research Blog"
    Biography = "If you have any questions or want to keep in touch, feel free to mail me to erick.tornero@ucsp.edu.pe"
    
    Avatar = "images/avatar.jpg"
    ShowBio = true
    PermalinkText = "🔗"
    EmailAddress = "erick.tornero@ucsp.edu.pe"
    GitHubUser = "erickTornero"
    LinkedInUser = "ericktornero"
    TwitterUser = "erickTorneroT"

    [params.indieWeb]
        EmailAddress = "erick.tornero@ucsp.edu.pe"
        Country = "Perú"
        City = "Arequipa"