baseURL = "http://example.org/"
languageCode = "en-us"
title = "Research blog"
theme = "indigo"
publishDir = "docs"

[languages]
  [languages.en]
    title = "Research blog"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "cd home"
      logoHomeLink = "/"